### ISSUE TITLE
Upgrade to version 3.5.0

### ISSUE THREAD

**Issue by dnascimento** [mparticle-integrations/mparticle-javascript-integration-appboy#47]
Upgrade to latest Braze version

**Comment by rmi22186** [comment]
Hi - thanks for your request.  We do have this in our backlog right now and hope to get to it soon.  Can you go through your customer success manager to ensure we add your company to the request?

**Comment by rmi22186** [comment]
Hi @dnascimento  - We have upgraded to 3.5.0!  There is a caveat though.  Since there are breaking changes to the Braze SDK from v2 to v3 ([Braze docs here](https://www.braze.com/docs/developer_guide/platform_integration_guides/web/changelog/#300)), we are doing a phased rollout:
* If you load mParticle via NPM, you can upgrade right away.  The new npm module can be found [here](https://www.npmjs.com/package/@mparticle/web-braze-kit) - note that we renamed this from appboy to braze so you'll have to update your package.json dependency.
* If you load mParticle via our CDN/snippet, you will automatically get the update on 6/8/2022. This will give all of our customers ample time to make any potential changes to their code base to avoid running into any issues around the Braze SDK breaking changes.

See [our docs](https://docs.mparticle.com/integrations/braze/event) here for more details around the breaking changes and how to defensively code around them to prepare for when the CDN gets the new version.

The new mParticle Braze web kit repo is [here](https://github.com/mparticle-integrations/mparticle-javascript-integration-braze) and includes this info in the README as well (this info is also repeated in the readme of the current appboy repo you are in).   Finally, our customer success team has also reached out to all of our clients with this information.

Closing this ticket, let us know if you have any questions.
